name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
    - name: make
      run: make
    - name: make check
      run: make check
    - name: runServer
      run: ./server localhost 32000 
    - name: run1
      run: ./sh13 localhost 32000 localhost 32001 a
    - name: run2
      run: ./sh13 localhost 32000 localhost 32002 b
    - name: run3
      run: ./sh13 localhost 32000 localhost 32003 c
    - name: run4
      run: ./sh13 localhost 32000 localhost 32004 d
