name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install_dependencies
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update
        sudo apt-get install libsdl2-2.0
        sudo apt-get install libsdl2-dev
        sudo apt-get install libsdl2-mixer-dev
        sudo apt-get install libsdl2-image-dev
        sudo apt-get install libsdl2-ttf-dev
        sudo apt-get install libsdl2-gfx-dev
    - name: make
      run: make
    - name: make check
      run: make check
    - name: run
      run: |
        ./server localhost 32000 
        ./sh13 localhost 32000 localhost 32001 a
        ./sh13 localhost 32000 localhost 32002 b
        ./sh13 localhost 32000 localhost 32003 c
        ./sh13 localhost 32000 localhost 32004 d
